### ISSUE TITLE
Further menu styling improvements

### ISSUE THREAD

**Issue by samglover** [samglover/client-power-tools#68]
It would be a good idea to include some additional styles to prevent weird formatting conflicts. For example, these are necessary in the [Themedd theme](https://easydigitaldownloads.com/downloads/themedd/).

```css
.customize-cpt #cpt-nav .menu > .menu-item {
  margin: 0;
}

.customize-cpt #cpt-nav .menu > .menu-item-has-children > .sub-menu {
  margin: 0;
}
```

Although it's worth considering how much to add, here. The more styling CPT does, the more likely the theme won't override all the customizations so that the user will have to add custom CSS.
